---
title: "Course Schedule"
tbl-colwidths: [13,8,20,16,21,5,5,4,5,4]
editor: visual
---

```{r}
#| label: setup
#| include: false
library(lubridate)

tue <- as_date("2026-08-25")
thu <- tue + days(2)

advdate <- function(day, week) {
  date <- (day + weeks(week))
  dm <- paste(month(date, label = TRUE)," ", day(date))
  return(dm)
}
```

This page displays an outline of the topics, content, and assignments for the term. Our class meets **Tuesdays and Thursdays, 11:10 a.m.--12:25 p.m., in the Hall of Government, Room 102.** Each topic spans one week (Tuesday and Thursday). **Note that all of your coding and project assignments are due on the Monday after they are assigned at 11:59 p.m.**

::: column-screen-inset-right
| Topic | Date | Skills | Packages | Functions | Readings | Reference | Slides | Videos | Assignments |
|:------:|--------|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|
| [Getting Started](/modules/getting-started.qmd "Getting Started") | `r advdate(tue,0)` | Course overview + inspiring examples: make a map, plot democracy over time, UN voting trends |  |  |  |  | [🖥️](slides/week-2.2.qmd) |  |  |
|  | `r advdate(thu,0)` | R, RStudio, Quarto & GitHub | `tidyverse`, `quarto` |  |  | [📖](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/ "project-oriented workflow") [📖](https://happygitwithr.com/ "Happy Git, chaps 4, 6, 7, 9 & 12") | [🖥️](slides/week-2.1.qmd) | [🖥️](https://youtu.be/gssjyyl7vxI "R and RStudio")[🖥️](https://youtu.be/c654j7aQjcg "Quarto")[🖥️](https://youtu.be/ApvMnAfQe8A "Getting started with GitHub") |  |
| [Charting with ggplot2](/modules/module-2.1.qmd "Charting with ggplot2") | `r advdate(tue,1)` | Bar charts & histograms | `ggplot2` | `ggplot()`, `geom_col()`, `geom_histogram()`, `aes()`, `labs()` |  | [📖](https://r4ds.hadley.nz/data-visualize.html "r4ds, 2")[📖](https://r4ds.hadley.nz/communication.html#labels "r4ds, 12.2") | [🖥️](slides/week-5.1.qmd) | [🖥️](https://youtu.be/hl02sVTyCRA "Bar charts")[🖥️](https://youtu.be/LuNDAIQXx9w "Histograms") |  |
|  | `r advdate(thu,1)` | Line charts & scatter plots | `ggplot2`, `scales` | `geom_line()`, `geom_point()`, `geom_smooth()`, `scale_x_log10()`, `label_number()`, `geom_text()` |  | [📖](https://r4ds.hadley.nz/layers.html "r4ds, 10.1-10.4") | [🖥️](slides/week-5.2.qmd) | [🖥️](https://youtu.be/cHos9y261SQ "Line charts")[🖥️](https://youtu.be/Cvme3C268wE "Scatter plots") |  |
| [Color, themes & annotations](/modules/module-2.2.qmd "Color, themes & annotations") | `r advdate(tue,2)` | Color schemes | `tidyr`, `colorBlindness`, `dplyr`, `viridis`, `RColorBrewer` | `drop_na()`, `cvdPlot()`, `scale_fill_manual()`, `scale_fill_viridis_d()`, `scale_fill_brewer()`, `scale_color_manual()`, `scale_color_viridis_d()`, `scale_color_brewer()` | [📖](https://www-jstor-org.proxygw.wrlc.org/stable/1951731?seq=8 "Lipset") | [📖](https://r4ds.hadley.nz/communication.html#scales "r4ds, 12.4") | [🖥️](slides/week-6.1.qmd) | [🖥️](https://youtu.be/fBCtSjg_-Ik "Color schemes") |  |
|  | `r advdate(thu,2)` | Themes, annotations & interactivity | `ggplot2`, `plotly` | `theme_minimal()`, `annotate()`, `geom_hline()`, `geom_vline()`, `ggplotly()`, `layout()` |  | [📖](https://r4ds.hadley.nz/communication.html#annotations "r4ds, 12.3 & 12.5") | [🖥️](slides/week-6.2.qmd) | [🖥️](https://youtu.be/Le0OJXdsy3o "Themes")[🖥️](https://youtu.be/uEpBMgWilXc "Annotations")[🖥️](https://youtu.be/T-7jtbcwaJ0 "Interactivity") | [🧮](/assignments/coding-assignment-1.qmd "Coding Assignment 1") |
| [Reading & reshaping data](/modules/module-1.1.qmd "Reading & reshaping data") | `r advdate(tue,3)` | Read data into R | `readr`, `dplyr` | `read_csv()`, `glimpse()` |  | [📖](https://r4ds.hadley.nz/data-import.html#introduction "r4ds 8.1 & 8.2") | [🖥️](slides/week-3.1.qmd) | [🖥️](https://youtu.be/YLOaKB8dfF4 "Downloading World Bank data")[🖥️](https://youtu.be/XOGXn8IiHK8 "Reading data from a flat file") |  |
|  | `r advdate(thu,3)` | Reshape & clean data | `tidyr`, `dplyr` | `pivot_longer()`, `mutate()`, `mutate_at()`, `substring()` |  | [📖](https://r4ds.hadley.nz/data-tidy.html "r4ds 6.1 & 6.3") | [🖥️](slides/week-3.2.qmd) | [🖥️](https://youtu.be/ud36szsO9a4 "Reshaping data")[🖥️](https://youtu.be/-JT8JSR1z5A "Strings & variable types")[🖥️](https://youtu.be/7bgoebbzfKQ "Cleaning var names") |  |
| [Importing & merging data](/modules/module-1.2.qmd "Importing & merging data") | `r advdate(tue,4)` | Download data from APIs | `wbstats`, `vdemdata`, `dplyr`, `janitor` | `wb_data()`, `vdem`, `select()`, `filter()`, `case_match()`, `round_to_fraction()` | [📖](https://link.springer.com/article/10.1057/palgrave.ap.5500151 "Norris") |  | [🖥️](slides/week-4.1.qmd) | [🖥️](https://youtu.be/cBRTP2imt_o "Download data from the World Bank")[🖥️](https://youtu.be/7CvYTeMP_PU "Filter data and select variables") |  |
|  | `r advdate(thu,4)` | Merge, group, summarize & arrange | `countrycode`, `dplyr`, `readr` | `countrycode()`, `left_join()`, `write_csv()`, `group_by()`, `summarize()`, `arrange()` |  | [📖](https://r4ds.hadley.nz/joins.html#sec-mutating-joins "r4ds, 20.3") [📖](https://r4ds.hadley.nz/data-transform.html#groups "r4ds, 4.5") | [🖥️](slides/week-4.2.qmd) | [🖥️](https://youtu.be/ZGD0kO_iwAM "Add country codes")[🖥️](https://youtu.be/wNF3ZPneHWw "Merge two data frames")[🖥️](https://youtu.be/2nX9p6arQjg "Group, summarize and arrange") | [🧮](/assignments/coding-assignment-2.qmd "Coding Assignment 2") |
| [Choropleth maps](/modules/module-3.1.qmd "Choropleth maps") | `r advdate(tue,5)` | Map data with choropleth maps | `rnaturalearth`, `ggplot2`, `ggthemes`, `viridis` | `ne_countries()`, `geom_sf()`, `theme_map()`, `theme()`, `scale_fill_viridis_c()` |  |  | [🖥️](slides/week-7.1.qmd) | [🖥️](https://youtu.be/HB3PMF93hzs "Choropleth maps")[🖥️](https://youtu.be/5RnnGov3Iw4 "Map World Bank data") |  |
|  | `r advdate(thu,5)` | Turn your map into a function |  | `source()`, `function()` | [📖](https://www-jstor-org.proxygw.wrlc.org/stable/j.ctt7s3wz.10 "Ross, Chapter 3") | [📖](https://r4ds.hadley.nz/functions "r4ds, chap. 25") | [🖥️](slides/week-7.2.qmd) | [🖥️](https://youtu.be/m42vrbEEHT4 "Turn your map into a function") |  |
| [Interactive maps](/modules/module-3.2.qmd "Interactive maps") | `r advdate(tue,6)` | Make a leaflet map | `sf`, `leaflet`, `htmltools` | `leaflet()`, `st_as_sf()`, `addTiles()`, `addMarkers()`, `addProviderTiles()` |  |  | [🖥️](slides/week-8.1.qmd) | [🖥️](https://youtu.be/If2PwFv90iI "Upload UCDP data")[🖥️](https://youtu.be/hHUPqgHRqYU "Make a leaflet map") |  |
|  | `r advdate(thu,6)` | Customize your interactive map | `leaflet` | `addProviderTiles()`, `setView()`, `addLegend()` |  |  |  | [🖥️](https://youtu.be/qLYeSsoDvgs "Customize your map") | [🧮](/assignments/coding-assignment-3.qmd "Coding Assignment 3") |
|  | `r advdate(tue,7)` | No class, fall break |  | 🍁🍂🎃 |  |  |  |  |  |
|  | `r advdate(thu,7)` | **Flex session:** what makes good data viz? + brainstorm your final project |  |  |  |  |  |  | [✍️](project/project-assignment-1.qmd "Project Assignment 1") |
| [Tables](/modules/module-4.1.qmd "Tables") | `r advdate(tue,8)` | Explore tabular data | `tidycensus`, `dplyr`, `stringr`, `kableExtra` | `census_api_key()`, `load_variables()`, `get_acs()`, `rename()`, `str_remove()`, `kable()`, `slice_max()`, `slice_min()`, `bind_rows()` |  |  | [🖥️](slides/week-9.1.qmd) | [🖥️](https://www.youtube.com/embed/wo9vZccmqwc "Working with tidycensus")[🖥️](https://www.youtube.com/embed/wo9vZccmqwc "Explore data with kableExtra") |  |
|  | `r advdate(thu,8)` | Make a `gt` table & confidence intervals | `gt`, `ggplot2` | `gt()`, `tab_header()`, `cols_label()`, `fmt_currency()`, `tab_source_note()`, `cols_align()`, `gtsave()`, `geom_errorbar()` |  |  | [🖥️](slides/week-9.2.qmd) | [🖥️](https://www.youtube.com/embed/wo9vZccmqwc "Make a gt table")[🖥️](https://www.youtube.com/embed/wo9vZccmqwc "Make a coefficient plot") |  |
| [Models & coefficient plots](/modules/module-4.2.qmd "Models & coefficient plots") | `r advdate(tue,9)` | Run models & display regression tables | `peacesciencer`, `broom`, `dplyr` | `create_stateyears()`, `add_ucdp_acd()`, `add_democracy()`, `tidy()`, `mutate_if()`, `glm()`, `binomial()` | [📖](https://www.jstor.org/stable/3118222 "Fearon & Laitin") |  | [🖥️](slides/week-10.1.qmd) | 🖥️ |  |
|  | `r advdate(thu,9)` | Regression tables & coefficient plots | `modelsummary` | `list()`, `modelsummary()`, `modelplot()`, `rev()` |  |  |  | 🖥️🖥️ | [🧮](/assignments/coding-assignment-4.qmd "Coding Assignment 4") |
| [Building a Shiny app](/modules/module-5.1.qmd "Building a Shiny app") | `r advdate(tue,10)` | App setup & building the UI | `dplyr`, `shiny` | `fluidPage()`, `titlePanel()`, `sidebarLayout()`, `sidebarPanel()`, `selectInput()`, `mainPanel()`, `plotOutput()` |  |  | [🖥️](slides/week-11.1.qmd) | 🖥️🖥️ |  |
|  | `r advdate(thu,10)` | Building the server | `shiny` | `renderPlot()`, `reactive()`, `shinyApp()` |  |  | [🖥️](slides/week-11.2.qmd) | 🖥️ | [✍️](project/project-assignment-2.qmd "Project Assignment 2") |
| [Extending & deploying your app](/modules/module-5.2.qmd "Extending & deploying your app") | `r advdate(tue,11)` | Add inputs & a time-series app | `fredr`, `shiny` | `fredr_set_key()`, `reactive()`, `sliderInput()`, `fredr()`, `fred_indicator()` | [📖](https://muse-jhu-edu.proxygw.wrlc.org/article/225602 "Huntington") |  | [🖥️](slides/week-12.1.qmd) | 🖥️🖥️ |  |
| [Deploying & sharing](/modules/module-6.2.qmd "Deploying & sharing your app") | `r advdate(thu,11)` | Deploy & share your app (shinyapps.io, shinylive) | `shiny`, `rsconnect` |  |  |  | [🖥️](slides/week-13.2.qmd) | 🖥️ | [🧮](/assignments/coding-assignment-5.qmd "Coding Assignment 5") |
| [Project studio](/modules/module-6.1.qmd "Project studio") | `r advdate(tue,12)` | Build your app (studio) |  |  |  |  | [🖥️](slides/week-13.1.qmd) |  |  |
|  | `r advdate(thu,12)` | Troubleshooting clinic (studio) |  |  |  |  |  |  |  |  |
|  | `r advdate(tue,13)` | No class, Thanksgiving break |  | 🦃🥧🍂 |  |  |  |  |  |
|  | `r advdate(thu,13)` | No class, Thanksgiving break |  |  |  |  |  |  |  |  |
|  | `r advdate(tue,14)` | Project studio: peer feedback |  |  |  |  |  |  |  |  |
|  | `r advdate(thu,14)` | Project studio: dry-run presentations |  |  |  |  |  |  |  |  |
|  | `r advdate(tue,15)` | Final presentations / lightning talks |  |  |  |  |  |  |  | [✍️](project/project-assignment-3.qmd "Project Assignment 3") |
:::
